In [4]:
import numpy as np

In [5]:
print((1,2)==True)

False


In [11]:
input_array = np.array([ [0, 0, 1, 0, 0], [0, 1, 0, 1, 0], [0, 0, 0, 0, 0], [0, 1, 0, 1, 0], [0, 0, 1, 0, 0] ])

In [14]:
import torch

result = torch.abs(torch.tensor(500) / 1.5)
print(result)


[[0 0 1 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 1 0 0]]
[[0 0 0]
 [0 1 0]
 [1 0 0]]


ValueError: could not broadcast input array from shape (3,3) into shape (4,4)

In [5]:
print(np.argwhere(input_array))

tensor(333.3333)


In [1]:
import random

# Пример списка объектов (замените своими изображениями)
obj_images = ["img1", "img2", "img3", "img4", "img5", "img6", "img7", "img8", "img9", "img10"]

# Диапазон количества изображений
a, b = 3, 5

# Генерируем случайное количество изображений для выбора
n = random.randint(a, b)

# Выбираем случайные изображения
selected_images = random.sample(obj_images, n)

print(f"Выбрано {n} изображений: {selected_images}")


Выбрано 3 изображений: ['img3', 'img6', 'img8']


In [ ]:
import cv2
import numpy as n
import tkinter as tk
from tkinter import filedialog
import numpy as np
import pprint

In [1]:


# Создаем окно Tkinter и скрываем его
root = tk.Tk()
root.withdraw()

# Открываем диалоговое окно для выбора файла
file_path = filedialog.askopenfilename()

# Проверяем, выбран ли файл
if file_path:
    # Загружаем изображение
    image = cv2.imread(file_path)
im = np.array(image)
channel = image[:, :, 2]

thresh = 127
# Бинаризация изображения (хотя она уже бинарная, но для ясности кода)
_, binary_img = cv2.threshold(channel, thresh, 255, cv2.THRESH_BINARY)

# Нахождение контуров
contours, hierarchy = cv2.findContours(binary_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
for i, contour in enumerate(contours):
    print(f"Контур {i+1} содержит {len(contour)} точек.")
    
    # Проходим по каждой точке контура
    for point in contour:
        x, y = point[0]  
        print(channel[x,y]) 
# for i, contour in enumerate(contours):
#     print(f"Контур {i+1} содержит {len(contour)} точек.")
# 
# for point in contours:
#     x = point  # x, y координаты точки на контуре
#     print(x.shape)
# cv2.drawContours(im, contours, -1, (0, 255, 0), 2)
# cv2.imshow('Contours', im)ь
# cv2.waitKey(0)
# cv2.destroyAllWindows()


In [2]:
print(im)

Контур 1 содержит 96 точек.
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255


IndexError: index 1199 is out of bounds for axis 0 with size 938

In [4]:
image = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]], dtype=np.uint8)

# Ядро для морфологических операций
kernel = np.ones((3, 3), np.uint8)

# Применяем закрытие
closed = cv2.morphologyEx(image, cv2.MORPH_CLOSE, kernel)

# Применяем эрозию
eroded = cv2.erode(closed, kernel)

print("Original Image Shape:", image.shape)
print("Closed Image Shape:", closed.shape)
print("Eroded Image Shape:", eroded.shape)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [52]:
print(closed)
print(eroded)

Original Image Shape: (3, 3)
Closed Image Shape: (3, 3)
Eroded Image Shape: (3, 3)


In [53]:
def put(x, y, this, on_this):
    bh, bw, _ = on_this.shape
    h, w, a = this.shape

    if 1 - w > x or x > bw - 1 or 1 - h > y or y > bh - 1:
        raise Exception("out of bounds")
    # false height, true height
    fh, th = 0, h
    # false weight, true weight
    fw, tw = 0, w
    # fw = 20
    if x < 0:
        fw = -x
    # fh = 10
    if y < 0:
        fh = -y
    if h > bh - y:
        th = bh - y
    if w > bw - x:
        tw = bw - x
    bg = on_this.copy()
    # область вставки
    paste = bg[max(0, x):min(x + w, bw),max(0, y):min(y + h, bh)]
    # обьект который вставляем(обрезаный)
    # пока что выделяются тольло три канала
    # fw = 20
    # fh = 10
    # [20:100,10:50,:3]
    # fw = 0, fh = 0, tw = bw - x , th = bh - y
    obj = this[fw:tw, fh:th, :3]

    if a == 4:
        # Первая ось (0) отвечает за каналы (R, G, B),
        # Вторая ось (1) — высота,
        # Третья ось (2) — ширина.
        alpha = this[fw:tw, fh:th, -1] / 255
        #         [alpha] * 3 создаёт список, содержащий три одинаковых массива alpha:
        # [alpha, alpha, alpha]
        # [alpha, alpha, alpha]
        # После преобразования в np.array мы получаем трёхмерный массив с формой: shape=(3,h,w)

        # alpha_n — прозрачность для каждого из каналов (R, G, B).
        alpha_n = np.array([alpha] * 3).transpose((2, 1, 0))
        # alpha_t = 1.0 - alpha_n — прозрачность для фона,
        alpha_t = 1.0 - alpha_n
        # логика такова на картинке-обьекта alpha слой 1 и (0,1], если у нас есть обьект
        # мы умнажаем его rgb картинки-обьекта на alpha слой полниостью удаляем фон и
        bg[max(0, x):min(x + w, bw),max(0, y):min(y + h, bh)] = paste * alpha_t + obj * alpha_n
    else:
        bg[max(0, x):min(x + w, bw),max(0, y):min(y + h, bh)] = obj
    return bg

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
from scipy.signal import convolve2d

# Матрица Собеля
sobel_matrix1 = np.array([
    [1,  0,  -1],
    [2,  0,  -2],
    [1,  0,  -1]
])

sobel_matrix2 = np.array([
    [1, 2, 1],
    [0, 0, 0],
    [-1, -2, -1]
])
# Исходная матрица (5x5)
original_matrix1 = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1],
    [0, 0, 1, 1, 1],
    [0, 0, 1, 1, 1]
])
matrix = np.zeros((10, 10), dtype=int)

# Добавление L-образной фигуры в верхний левый угол
matrix[1:4, 1] = 1  # Вертикальная часть
matrix[1, 1:4] = 1  # Горизонтальная часть

# Добавление "зигзага" в правой части
matrix[2, 7:10] = 1
matrix[3, [7, 9]] = 1
matrix[4:7, 7] = 1
matrix[6, 8:10] = 1

# Добавление "стены" в середине
matrix[4:7, 5] = 1

print(matrix)
# Добавление паддинга (1 слой нулей вокруг матрицы)
padded_matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)

# Выполнение свёртки
result_matrix1 = convolve2d(padded_matrix, sobel_matrix1, mode='valid')
result_matrix2 = convolve2d(padded_matrix, sobel_matrix2, mode='valid')


print("\nРезультирующая матрица после свёртки (5x5):")
print(result_matrix1)
print(result_matrix2)


[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 1 1]
 [0 1 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 1 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Результирующая матрица после свёртки (5x5):
[[ 1  1  0 -1 -1  0  0  0  0  0]
 [ 3  2 -1 -2 -2  0  1  1  0 -1]
 [ 4  1 -3 -1 -1  0  3  2  0 -2]
 [ 3  0 -3  0  1  0  3  1 -1 -1]
 [ 1  0 -1  0  3  0  1  0 -3  0]
 [ 0  0  0  0  4  0  0  1 -3 -1]
 [ 0  0  0  0  3  0  0  2 -1 -2]
 [ 0  0  0  0  1  0  0  1  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
[[ 1  3  4  3  1  0  0  0  0  0]
 [ 1  2  1  0  0  0  1  3  4  3]
 [ 0 -1 -3 -3 -1  0  1  2  2  2]
 [-1 -2 -1  0  1  2  1 -1 -3 -3]
 [-1 -2 -1  0  1  2  1  0 -1 -2]
 [ 0  0  0  0  0  0  0  1  3  3]
 [ 0  0  0  0 -1 -2 -2 -2 -1  0]
 [ 0  0  0  0 -1 -2 -2 -3 -4 -3]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
